---
output:
  md_document:
    variant: markdown_github
    pandoc_args: --webtex=https://latex.codecogs.com/svg.latex?
bibliography: ../README.bib
---

# Mixed Generalized Survival Models

```{r setup, echo = FALSE, cache=FALSE}
local({
  if(!grepl("examples$", getwd()))
    setwd("examples")
})

knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>", fig.path = "fig-mgsm/", dpi = 124, 
  error = FALSE, cache.path = "cache-mgsm/")
options(digits = 4)
```

We simulate from

$$
\begin{align*}
-\Phi^{-1}(S(t\mid \vec x_{ij}, \vec z_{ij}, \vec u_i)) 
  &= \vec x_{ij}(t)^\top\vec\beta + \vec z_{ij}^\top\vec u_i \\
\vec U_i &\sim N(\vec 0, \Sigma) 
\end{align*}
$$
subject to independent censoring and estimate the model. 
The conditional hazard of the model is 

$$
h(t\mid  \vec x_{ij}, \vec z_{ij}, \vec u_i) = 
  \vec x_{ij}'(t)^\top\vec\beta
  \frac{\phi(-\vec x_{ij}(t)^\top\vec\beta - \vec z_{ij}^\top\vec u_i)}
       {\Phi(-\vec x_{ij}(t)^\top\vec\beta - \vec z_{ij}^\top\vec u_i)}
$$

The code to do the stimulation and to assign the model parameters is given 
below.

```{r assing_sim_dat}
# computes the time-varying fixed effects
x <- \(v) { v <- log(v); cbind(1, v, v^3) }
xp <- \(v) { v_org <- v; v <- log(v); cbind(0, 1, 3 * v^2) / v_org }

# generates the time-invariant covariates
gen_cov <- \(n) cbind(rnorm(n), runif(n) > .5)

# the fixed effects coefficients (beta)
beta <- c(-1, .25, .4, .5, 1)

admin_cens <- 5 # the administrative censoring time

# plot of the hazard when the other fixed effects are zero
par(mar = c(5, 5, 1, 1))
seq(1e-2, admin_cens, length.out = 1000) |>
  (\(vs)
   plot(vs, 
        {
          beta_use <- head(beta, -2)
          eta <- x(vs) %*% beta_use
          eta_p <- xp(vs) %*% beta_use
          eta_p * exp(dnorm(-eta, log = TRUE) - pnorm(-eta, log = TRUE))
        }, 
        xlim = c(1e-2, admin_cens), xlab = "Time", ylab = "Hazard", bty = "l", 
        xaxs = "i", yaxs = "i", type = "l")
  )()

grid()

# generates the random effect covariates
gen_rng_cov <- \(n) cbind(1, rnorm(n))

# the random effect covariance matrix
Sigma <- structure(c(0.96725, -0.1505, -0.1505, 0.27875), .Dim = c(2L, 2L))

# simulates a given number of clusters
sim_dat <- \(n_clusters)
  lapply(seq_len(n_clusters), \(id) {
    n_members <- sample.int(9L, 1L) + 2L
    U <- drop(mvtnorm::rmvnorm(1, sigma = Sigma))
    X <- gen_cov(n_members)
    Z <- gen_rng_cov(n_members)
    
    # find the event times
    offset <- X %*% tail(beta, NCOL(X)) + Z %*% U
    
    beta_use <- head(beta, -NCOL(X))
    y <- sapply(offset, \(o){
      rng <- runif(1)
      res <- uniroot(\(ti) rng - pnorm(-o - x(ti) %*% beta_use), 
                     c(1e-32, 10000), 
                     tol = 1e-10)
      res$root
    })
    
    cens <- pmin(admin_cens, runif(n_members, 0, 2 * admin_cens))
    
    colnames(X) <- paste0("X", 1:NCOL(X))
    colnames(Z) <- paste0("Z", 1:NCOL(Z))
    
    out <- list(event = y < cens, y = pmin(y, cens), X = X, Z = Z, 
                id = rep(id, n_members))
    
    c(out, list(df = do.call(cbind, out)))
  })
```

Next, we simulate from the model and estimate the model.

```{r fit_ex, cache = 1}
# simulate the data
set.seed(8401834)
dat <- sim_dat(2000L)
dat_full <- lapply(dat, `[[`, "df") |> do.call(what = rbind) |> data.frame()

mean(dat_full$event) # fraction of observed events
NROW(dat_full) # number of observations
# quantiles of the observed event times
subset(dat_full, event > 0)$y |> 
  quantile(probs = seq(0, 1, length.out = 11))

# fit the model with the stochastic spherical-radial rules
library(mixprobit)
system.time(
  res_sr <- fit_mgsm(
    formula = Surv(y, event) ~ X1 + X2, data = dat_full, id = id,
    rng_formula = ~ Z2, maxpts = c(1000L, 10000L), df = 8L, 
    method_use = "adaptive_spherical_radial"))

# fit the model with the CDF approach
system.time(
  res_cdf <- fit_mgsm(
    formula = Surv(y, event) ~ X1 + X2, data = dat_full, id = id,
    rng_formula = ~ Z2, maxpts = c(1000L, 10000L), df = 8L, 
    method_use = "cdf_approach"))
```

The results are shown below.

```{r show_fit_ex}
# the estimates are shown below
rbind(`Estimate spherical radial` = res_sr$beta_fixef, 
      `Estimate CDF` = res_cdf$beta_fixef,
      Truth = tail(beta, 2))

res_sr$Sigma # estimated covariance matrix
res_cdf$Sigma # estimated covariance matrix
Sigma # the true covariance matrix

# plot of the estimated hazard and the true hazard when the other fixed effects
# are zero
library(splines)
Xt_spline <- \(v) splineDesign(res_sr$A_knots, log(v), outer.ok = TRUE)
Xt_spline_prime <- \(v) splineDesign(
  res_sr$A_knots, log(v), derivs = 1, outer.ok = TRUE) / v

vs <- seq(1e-2, admin_cens, length.out = 1000)
# computes the hazard
cmp_haz <- \(x, xp, beta_use)
  sapply(vs, \(v){
    eta <- x(v) %*% beta_use
    eta_p <- xp(v) %*% beta_use
    eta_p * exp(dnorm(-eta, log = TRUE) - pnorm(-eta, log = TRUE))
  })

par(mar = c(5, 5, 1, 1))
matplot(
  vs, cbind(
    cmp_haz(x, xp, head(beta, -2)),
    cmp_haz(Xt_spline, Xt_spline_prime, res_sr$beta_spline),
    cmp_haz(Xt_spline, Xt_spline_prime, res_cdf$beta_spline)),
  type = "l", bty = "l", lty = 1:3, 
  col = "Black", xlab = "Time", ylab = "Hazard", xaxs = "i", yaxs = "i")
grid()

# the maximum likelihood
print(res_sr$logLik, digits = 8)
print(res_cdf$logLik, digits = 8)

# compare the variance on the log marginal likelihood of the two methods 
# while tracking the computation time
system.time(
  funcn_ests <- sapply(1:20, \(s) res_sr $fn(res_sr$optim$par, seed = s)))
sd(funcn_ests)
system.time(
  funcn_ests <- sapply(1:20, \(s) res_cdf$fn(res_sr$optim$par, seed = s)))
sd(funcn_ests)

# can be compared with say a Weibull model
survreg(Surv(y, event) ~ X1 + X2, data = dat_full) |> logLik()
```
