# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pmvnorm_cpp <- function(lower, upper, mean, cov, maxpts, abseps, releps) {
    .Call('_mixprobit_pmvnorm_cpp', PACKAGE = 'mixprobit', lower, upper, mean, cov, maxpts, abseps, releps)
}

aprx_binary_mix <- function(y, eta, Z, Sigma, mxvals, key, epsabs, epsrel) {
    .Call('_mixprobit_aprx_binary_mix', PACKAGE = 'mixprobit', y, eta, Z, Sigma, mxvals, key, epsabs, epsrel)
}

aprx_binary_mix_cdf <- function(y, eta, Z, Sigma, maxpts, abseps, releps) {
    .Call('_mixprobit_aprx_binary_mix_cdf', PACKAGE = 'mixprobit', y, eta, Z, Sigma, maxpts, abseps, releps)
}

set_GH_rule_cached <- function(b) {
    .Call('_mixprobit_set_GH_rule_cached', PACKAGE = 'mixprobit', b)
}

aprx_binary_mix_ghq <- function(y, eta, Z, Sigma, b) {
    .Call('_mixprobit_aprx_binary_mix_ghq', PACKAGE = 'mixprobit', y, eta, Z, Sigma, b)
}

aprx_binary_mix_brute <- function(y, eta, Z, Sigma, n_sim) {
    .Call('_mixprobit_aprx_binary_mix_brute', PACKAGE = 'mixprobit', y, eta, Z, Sigma, n_sim)
}

