# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pmvnorm_cpp <- function(lower, upper, mean, cov, maxpts, abseps, releps) {
    .Call('_mixprobit_pmvnorm_cpp', PACKAGE = 'mixprobit', lower, upper, mean, cov, maxpts, abseps, releps)
}

pmvnorm_cpp_restrict <- function(mean, cov, maxpts, abseps, releps, gradient = FALSE) {
    .Call('_mixprobit_pmvnorm_cpp_restrict', PACKAGE = 'mixprobit', mean, cov, maxpts, abseps, releps, gradient)
}

aprx_binary_mix <- function(y, eta, Z, Sigma, maxpts, abseps, releps, key = 2L, is_adaptive = FALSE) {
    .Call('_mixprobit_aprx_binary_mix', PACKAGE = 'mixprobit', y, eta, Z, Sigma, maxpts, abseps, releps, key, is_adaptive)
}

aprx_binary_mix_cdf <- function(y, eta, Z, Sigma, maxpts, abseps, releps) {
    .Call('_mixprobit_aprx_binary_mix_cdf', PACKAGE = 'mixprobit', y, eta, Z, Sigma, maxpts, abseps, releps)
}

aprx_binary_mix_cdf_get_ptr <- function(data, n_threads, gradient = FALSE) {
    .Call('_mixprobit_aprx_binary_mix_cdf_get_ptr', PACKAGE = 'mixprobit', data, n_threads, gradient)
}

aprx_binary_mix_cdf_eval <- function(ptr, beta, log_sds, maxpts, abseps, releps) {
    .Call('_mixprobit_aprx_binary_mix_cdf_eval', PACKAGE = 'mixprobit', ptr, beta, log_sds, maxpts, abseps, releps)
}

set_GH_rule_cached <- function(b) {
    .Call('_mixprobit_set_GH_rule_cached', PACKAGE = 'mixprobit', b)
}

aprx_binary_mix_ghq <- function(y, eta, Z, Sigma, b, is_adaptive = FALSE) {
    .Call('_mixprobit_aprx_binary_mix_ghq', PACKAGE = 'mixprobit', y, eta, Z, Sigma, b, is_adaptive)
}

aprx_binary_mix_brute <- function(y, eta, Z, Sigma, n_sim, n_threads = 1L) {
    .Call('_mixprobit_aprx_binary_mix_brute', PACKAGE = 'mixprobit', y, eta, Z, Sigma, n_sim, n_threads)
}

for_rngnorm_wrapper_test <- function(n, n_threads) {
    .Call('_mixprobit_for_rngnorm_wrapper_test', PACKAGE = 'mixprobit', n, n_threads)
}

